Update /api/set-notification-state
serlo/serlo.org pull request #586
Opened 2021-01-20 16:31 UTC by kulla

Update `/api/set-notification-state` so that it matches the signature in https://github.com/serlo/api.serlo.org/pull/189 (Move id parameter into request body load)

2021-01-20 16:45 UTC, inyono requested changes
LGTM. Blocked until api.serlo.org has the corresponding changes.

2021-01-25 00:49 UTC, kulla commented
@inyono Changes in api.serlo.org have been merged.

2021-01-26 12:21 UTC, inyono commented
Gonna merge this but the contract tests still need some work: https://github.com/serlo/api.serlo.org/issues/209

2021-01-26 12:21 UTC, inyono approved these changes

2021-01-26 12:22 UTC, merged